"""initial schema — M1.2 frozen schema materialization.

Materializes the frozen M1.1 SQLAlchemy metadata into PostgreSQL.

Authority:

    M1.0-A  Global Schema Conventions
    M1.0-B  15 Physical Table Contracts
    M1.0-C  M1C-01..04 cross-cluster integrity
    FC-01   CheckConstraint suffix naming
    FC-02   JSONB shape completion

Counts produced by this migration (frozen expectations):

    application tables:             15
    primary keys:                   15
    foreign keys:                   17
    UNIQUE constraints:             10
    CHECK constraints:              51
    explicit Index(...) objects:    33

This file is hand-authored rather than autogenerated because the
authoritative translation guarantees reference M1.0-A16/A17 (the frozen
naming convention), the M1C-01 composite foreign key, M1C-02 status
vocabulary, M1C-03 frozen vocabularies, M1C-04 SHA-256 regex CHECKs,
FC-01 CHECK suffixes, and FC-02 JSONB shape CHECKs. Each constraint /
index / column below corresponds 1:1 to the Base.metadata declaration
in ``app/models/*`` (commit 88c2748).

No model file was modified to produce this migration.
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e5b3cf21c1d12b64"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# ---------------------------------------------------------------------------
# Convenience: frozen PostgreSQL DDL fragments.
# ---------------------------------------------------------------------------
# SQLAlchemy renders gen_random_uuid() and now() via server_default so the
# migration DDL uses the same Server-side defaults as the frozen models.
GEN_RANDOM_UUID = sa.text("gen_random_uuid()")
NOW = sa.text("now()")


def upgrade() -> None:
    # -------------------------------------------------------------------
    # CỤM 1: INSTITUTIONAL MASTER DATA (3 tables)
    # -------------------------------------------------------------------

    # 1. lecturers ----------------------------------------------------------
    op.create_table(
        "lecturers",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=GEN_RANDOM_UUID,
        ),
        sa.Column("staff_code", sa.String(length=50), nullable=True),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("full_name_normalized", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("academic_rank", sa.String(length=50), nullable=True),
        sa.Column("academic_degree", sa.String(length=50), nullable=True),
        sa.Column("position", sa.String(length=100), nullable=True),
        sa.Column("department", sa.String(length=150), nullable=True),
        sa.Column("faculty", sa.String(length=150), nullable=True),
        sa.Column("repository_profile_url", sa.Text(), nullable=True),
        sa.Column("repository_profile_id", sa.String(length=100), nullable=True),
        sa.Column("orcid", sa.String(length=19), nullable=True),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("TRUE"),
        ),
        sa.Column(
            "version",
            sa.Integer(),
            nullable=False,
            server_default=sa.text("1"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=NOW,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=NOW,
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_lecturers_version")),
        sa.CheckConstraint(
            "orcid IS NULL OR orcid ~ "
            "'^[0-9]{4}-[0-9]{4}-[0-9]{4}-[0-9]{3}[0-9X]$'",
            name=op.f("ck_lecturers_orcid_format"),
        ),
    )
    op.create_index(
        op.f("uq_lecturers_staff_code"),
        "lecturers",
        ["staff_code"],
        unique=True,
        postgresql_where=sa.text("staff_code IS NOT NULL"),
    )
    op.create_index(
        op.f("uq_lecturers_email_ci"),
        "lecturers",
        [sa.text("lower(email)")],
        unique=True,
        postgresql_where=sa.text("email IS NOT NULL"),
    )
    op.create_index(
        op.f("uq_lecturers_orcid"),
        "lecturers",
        ["orcid"],
        unique=True,
        postgresql_where=sa.text("orcid IS NOT NULL"),
    )
    op.create_index(
        op.f("ix_lecturers_full_name_normalized"),
        "lecturers",
        ["full_name_normalized"],
        unique=False,
    )

    # 2. lecturer_source_snapshots -----------------------------------------
    op.create_table(
        "lecturer_source_snapshots",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=GEN_RANDOM_UUID,
        ),
        sa.Column("lecturer_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("source_system", sa.String(length=50), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("snapshot_hash", sa.String(length=64), nullable=False),
        sa.Column("raw_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("parser_version", sa.String(length=100), nullable=False),
        sa.Column("validation_status", sa.String(length=20), nullable=False),
        sa.Column("validation_errors", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=NOW,
        ),
        # Single-column FK to lecturers(id) ON DELETE RESTRICT (M1.0-A10).
        sa.ForeignKeyConstraint(
            ["lecturer_id"],
            ["lecturers.id"],
            name=op.f("fk_lecturer_source_snapshots_lecturer_id_lecturers"),
            ondelete="RESTRICT",
        ),
        # M1C-01 parent candidate key (id, lecturer_id) — explicit name.
        sa.UniqueConstraint(
            "id", "lecturer_id",
            name=op.f("uq_lecturer_source_snapshots_id_lecturer"),
        ),
        sa.CheckConstraint(
            "validation_status IN ('VALID', 'INVALID')",
            name=op.f("ck_lecturer_source_snapshots_validation_status"),
        ),
        sa.CheckConstraint(
            "snapshot_hash ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_lecturer_source_snapshots_snapshot_hash"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(raw_payload) = 'object'",
            name=op.f("ck_lecturer_source_snapshots_raw_payload_object"),
        ),
        sa.CheckConstraint(
            "validation_errors IS NULL OR jsonb_typeof(validation_errors) = 'array'",
            name=op.f("ck_lecturer_source_snapshots_validation_errors_array"),
        ),
    )
    op.create_index(
        op.f("ix_lecturer_source_snapshots_lecturer_id"),
        "lecturer_source_snapshots",
        ["lecturer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_snapshots_source_lookup"),
        "lecturer_source_snapshots",
        ["source_system", "source_url", "fetched_at"],
        unique=False,
    )

    # 3. lecturer_known_publications ---------------------------------------
    op.create_table(
        "lecturer_known_publications",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=GEN_RANDOM_UUID,
        ),
        sa.Column("lecturer_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("snapshot_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("title_raw", sa.Text(), nullable=False),
        sa.Column("title_normalized", sa.Text(), nullable=False),
        sa.Column("doi_raw", sa.String(length=255), nullable=True),
        sa.Column("doi_normalized", sa.String(length=255), nullable=True),
        sa.Column("source_title_raw", sa.Text(), nullable=True),
        sa.Column("published_year", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=NOW,
        ),
        # M1C-01 composite FK: (snapshot_id, lecturer_id) -> (id, lecturer_id).
        sa.ForeignKeyConstraint(
            ["snapshot_id", "lecturer_id"],
            ["lecturer_source_snapshots.id", "lecturer_source_snapshots.lecturer_id"],
            name=op.f("fk_lecturer_known_publications_snapshot_lecturer"),
            ondelete="RESTRICT",
        ),
        sa.CheckConstraint(
            "published_year IS NULL OR published_year BETWEEN 1000 AND 9999",
            name=op.f("ck_lecturer_known_publications_published_year"),
        ),
    )
    op.create_index(
        op.f("ix_lecturer_known_publications_lecturer_id"),
        "lecturer_known_publications",
        ["lecturer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lecturer_known_publications_snapshot_id"),
        "lecturer_known_publications",
        ["snapshot_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_known_pubs_lecturer_year"),
        "lecturer_known_publications",
        ["lecturer_id", "published_year"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lecturer_known_publications_doi"),
        "lecturer_known_publications",
        ["doi_normalized"],
        unique=False,
        postgresql_where=sa.text("doi_normalized IS NOT NULL"),
    )

    # -------------------------------------------------------------------
    # CỤM 2: SCOPUS RAW INGESTION (2 tables)
    # -------------------------------------------------------------------

    # 4. scopus_imports ----------------------------------------------------
    op.create_table(
        "scopus_imports",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=GEN_RANDOM_UUID,
        ),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("file_sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "total_records",
            sa.Integer(),
            nullable=False,
            server_default=sa.text("0"),
        ),
        sa.Column(
            "valid_records",
            sa.Integer(),
            nullable=False,
            server_default=sa.text("0"),
        ),
        sa.Column(
            "invalid_records",
            sa.Integer(),
            nullable=False,
            server_default=sa.text("0"),
        ),
        sa.Column(
            "status",
            sa.String(length=20),
            nullable=False,
            server_default=sa.text("'RECEIVED'"),
        ),
        sa.Column("error_summary", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "version",
            sa.Integer(),
            nullable=False,
            server_default=sa.text("1"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=NOW,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=NOW,
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_scopus_imports_version")),
        sa.CheckConstraint(
            "total_records >= 0 AND valid_records >= 0 AND invalid_records >= 0",
            name=op.f("ck_scopus_imports_record_counts"),
        ),
        sa.CheckConstraint(
            "file_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_scopus_imports_file_sha256"),
        ),
        sa.CheckConstraint(
            "status IN ('RECEIVED', 'PARSING', 'VALIDATED', 'STAGED', "
            "'APPLIED', 'FAILED', 'CANCELLED')",
            name=op.f("ck_scopus_imports_status"),
        ),
        sa.CheckConstraint(
            "error_summary IS NULL OR jsonb_typeof(error_summary) = 'object'",
            name=op.f("ck_scopus_imports_error_summary_object"),
        ),
    )
    op.create_index(
        op.f("ix_scopus_imports_file_sha256"),
        "scopus_imports",
        ["file_sha256"],
        unique=False,
    )
    op.create_index(
        op.f("ix_scopus_imports_status"),
        "scopus_imports",
        ["status"],
        unique=False,
    )

    # 5. raw_scopus_records ------------------------------------------------
    op.create_table(
        "raw_scopus_records",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=GEN_RANDOM_UUID,
        ),
        sa.Column("import_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("row_number", sa.Integer(), nullable=False),
        sa.Column("row_hash", sa.String(length=64), nullable=False),
        sa.Column("eid_raw", sa.Text(), nullable=True),
        sa.Column("doi_raw", sa.Text(), nullable=True),
        sa.Column("raw_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("validation_status", sa.String(length=20), nullable=False),
        sa.Column("validation_errors", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=NOW,
        ),
        sa.ForeignKeyConstraint(
            ["import_id"],
            ["scopus_imports.id"],
            name=op.f("fk_raw_scopus_records_import_id_scopus_imports"),
            ondelete="RESTRICT",
        ),
        sa.UniqueConstraint(
            "import_id", "row_number",
            name=op.f("uq_raw_scopus_records_import_row"),
        ),
        sa.CheckConstraint("row_number >= 1", name=op.f("ck_raw_scopus_records_row_number")),
        sa.CheckConstraint(
            "validation_status IN ('VALID', 'INVALID')",
            name=op.f("ck_raw_scopus_records_validation_status"),
        ),
        sa.CheckConstraint(
            "row_hash ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_raw_scopus_records_row_hash"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(raw_payload) = 'object'",
            name=op.f("ck_raw_scopus_records_raw_payload_object"),
        ),
        sa.CheckConstraint(
            "validation_errors IS NULL OR jsonb_typeof(validation_errors) = 'array'",
            name=op.f("ck_raw_scopus_records_validation_errors_array"),
        ),
    )
    op.create_index(
        op.f("ix_raw_scopus_records_eid_raw"),
        "raw_scopus_records",
        ["eid_raw"],
        unique=False,
        postgresql_where=sa.text("eid_raw IS NOT NULL"),
    )
    op.create_index(
        op.f("ix_raw_scopus_records_doi_raw"),
        "raw_scopus_records",
        ["doi_raw"],
        unique=False,
        postgresql_where=sa.text("doi_raw IS NOT NULL"),
    )

    # -------------------------------------------------------------------
    # CỤM 3: CANONICAL PUBLICATIONS & AUTHORS (5 tables)
    # -------------------------------------------------------------------

    # 6. publications -----------------------------------------------------
    op.create_table(
        "publications",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=GEN_RANDOM_UUID,
        ),
        # M1.0-A13: eid MUST be UNIQUE.
        sa.Column("eid", sa.Text(), nullable=False),
        sa.Column("doi", sa.String(length=255), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("title_normalized", sa.Text(), nullable=False),
        sa.Column("source_title", sa.Text(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("volume", sa.Text(), nullable=True),
        sa.Column("issue", sa.Text(), nullable=True),
        sa.Column("art_no", sa.Text(), nullable=True),
        sa.Column("page_start", sa.Text(), nullable=True),
        sa.Column("page_end", sa.Text(), nullable=True),
        # C3-03: cited_by_count nullable, NULL != 0.
        sa.Column("cited_by_count", sa.Integer(), nullable=True),
        sa.Column("document_type", sa.String(length=50), nullable=True),
        sa.Column("publication_stage", sa.String(length=50), nullable=True),
        sa.Column("open_access_status", sa.String(length=50), nullable=True),
        sa.Column(
            "version",
            sa.Integer(),
            nullable=False,
            server_default=sa.text("1"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=NOW,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=NOW,
        ),
        # M1.0-A13: UNIQUE on eid. Declared explicitly.
        sa.UniqueConstraint("eid", name=op.f("uq_publications_eid")),
        sa.CheckConstraint("btrim(eid) <> ''", name=op.f("ck_publications_eid_not_empty")),
        sa.CheckConstraint("version >= 1", name=op.f("ck_publications_version")),
        sa.CheckConstraint(
            "year IS NULL OR year BETWEEN 1000 AND 9999",
            name=op.f("ck_publications_year_range"),
        ),
        sa.CheckConstraint(
            "cited_by_count IS NULL OR cited_by_count >= 0",
            name=op.f("ck_publications_cited_by_count"),
        ),
    )
    op.create_index(
        op.f("ix_publications_doi"),
        "publications",
        ["doi"],
        unique=False,
        postgresql_where=sa.text("doi IS NOT NULL"),
    )
    op.create_index(
        op.f("ix_publications_year"),
        "publications",
        ["year"],
        unique=False,
    )

    # 7. publication_raw_sources ------------------------------------------
    op.create_table(
        "publication_raw_sources",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=GEN_RANDOM_UUID,
        ),
        sa.Column("publication_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("raw_record_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=NOW,
        ),
        sa.ForeignKeyConstraint(
            ["publication_id"],
            ["publications.id"],
            name=op.f("fk_publication_raw_sources_publication_id_publications"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["raw_record_id"],
            ["raw_scopus_records.id"],
            name=op.f("fk_publication_raw_sources_raw_record_id_raw_scopus_records"),
            ondelete="RESTRICT",
        ),
        # C3-05: a raw record maps to at most one canonical publication.
        sa.UniqueConstraint("raw_record_id", name=op.f("uq_publication_raw_sources_raw_record_id")),
    )
    op.create_index(
        op.f("ix_publication_raw_sources_publication_id"),
        "publication_raw_sources",
        ["publication_id"],
        unique=False,
    )

    # 8. scopus_authors ---------------------------------------------------
    op.create_table(
        "scopus_authors",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=GEN_RANDOM_UUID,
        ),
        sa.Column("scopus_id", sa.Text(), nullable=False),
        sa.Column("preferred_name", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=NOW,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=NOW,
        ),
        sa.UniqueConstraint("scopus_id", name=op.f("uq_scopus_authors_scopus_id")),
        sa.CheckConstraint(
            "btrim(scopus_id) <> ''",
            name=op.f("ck_scopus_authors_scopus_id_not_empty"),
        ),
    )

    # 9. scopus_author_name_variants --------------------------------------
    op.create_table(
        "scopus_author_name_variants",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=GEN_RANDOM_UUID,
        ),
        sa.Column("scopus_author_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("variant_type", sa.String(length=30), nullable=False),
        sa.Column("variant_name", sa.String(length=255), nullable=False),
        sa.Column("variant_name_normalized", sa.String(length=255), nullable=False),
        sa.Column("first_seen_raw_record_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=NOW,
        ),
        sa.ForeignKeyConstraint(
            ["scopus_author_id"],
            ["scopus_authors.id"],
            name=op.f("fk_scopus_author_name_variants_scopus_author_id_scopus_authors"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["first_seen_raw_record_id"],
            ["raw_scopus_records.id"],
            name=op.f("fk_scopus_author_name_variants_first_seen_raw_record_id_raw_scopus_records"),
            ondelete="RESTRICT",
        ),
        sa.UniqueConstraint(
            "scopus_author_id", "variant_type", "variant_name",
            name=op.f("uq_author_name_variants"),
        ),
        sa.CheckConstraint(
            "variant_type IN ('AUTHOR_DISPLAY', 'AUTHOR_FULL_NAME')",
            name=op.f("ck_scopus_author_name_variants_variant_type"),
        ),
    )
    op.create_index(
        op.f("ix_author_name_variants_normalized"),
        "scopus_author_name_variants",
        ["variant_name_normalized"],
        unique=False,
    )
    op.create_index(
        op.f("ix_author_name_variants_raw_source"),
        "scopus_author_name_variants",
        ["first_seen_raw_record_id"],
        unique=False,
    )

    # 10. publication_authors ---------------------------------------------
    op.create_table(
        "publication_authors",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=GEN_RANDOM_UUID,
        ),
        sa.Column("publication_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("scopus_author_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("author_order", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=NOW,
        ),
        # M1.0-A11: composition child -> ON DELETE CASCADE.
        sa.ForeignKeyConstraint(
            ["publication_id"],
            ["publications.id"],
            name=op.f("fk_publication_authors_publication_id_publications"),
            ondelete="CASCADE",
        ),
        # M1.0-A10: RESTRICT for the non-composition reference.
        sa.ForeignKeyConstraint(
            ["scopus_author_id"],
            ["scopus_authors.id"],
            name=op.f("fk_publication_authors_scopus_author_id_scopus_authors"),
            ondelete="RESTRICT",
        ),
        sa.UniqueConstraint(
            "publication_id", "author_order",
            name=op.f("uq_publication_authors_order"),
        ),
        sa.UniqueConstraint(
            "publication_id", "scopus_author_id",
            name=op.f("uq_publication_authors_author"),
        ),
        sa.CheckConstraint(
            "author_order >= 1",
            name=op.f("ck_publication_authors_author_order"),
        ),
    )
    op.create_index(
        op.f("ix_publication_authors_scopus_author_id"),
        "publication_authors",
        ["scopus_author_id"],
        unique=False,
    )

    # -------------------------------------------------------------------
    # CỤM 4: IDENTITY RESOLUTION & HUMAN REVIEW (3 tables)
    # -------------------------------------------------------------------

    # 11. lecturer_scopus_identities --------------------------------------
    op.create_table(
        "lecturer_scopus_identities",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=GEN_RANDOM_UUID,
        ),
        sa.Column("lecturer_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("scopus_author_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "status",
            sa.String(length=20),
            nullable=False,
            server_default=sa.text("'CANDIDATE'"),
        ),
        sa.Column("recommendation", sa.String(length=30), nullable=True),
        sa.Column("recommendation_algorithm_version", sa.String(length=100), nullable=True),
        sa.Column("recommended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "version",
            sa.Integer(),
            nullable=False,
            server_default=sa.text("1"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=NOW,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=NOW,
        ),
        sa.ForeignKeyConstraint(
            ["lecturer_id"],
            ["lecturers.id"],
            name=op.f("fk_lecturer_scopus_identities_lecturer_id_lecturers"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["scopus_author_id"],
            ["scopus_authors.id"],
            name=op.f("fk_lecturer_scopus_identities_scopus_author_id_scopus_authors"),
            ondelete="RESTRICT",
        ),
        sa.UniqueConstraint(
            "lecturer_id", "scopus_author_id",
            name=op.f("uq_lecturer_scopus_identities_pair"),
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_lecturer_scopus_identities_version")),
        sa.CheckConstraint(
            "status IN ('CANDIDATE', 'APPROVED', 'REJECTED', 'REVOKED')",
            name=op.f("ck_lecturer_scopus_identities_status"),
        ),
        sa.CheckConstraint(
            "recommendation IS NULL OR recommendation IN "
            "('MATCH', 'NO_MATCH', 'MANUAL_VERIFY')",
            name=op.f("ck_lecturer_scopus_identities_recommendation"),
        ),
        sa.CheckConstraint(
            "(recommendation IS NULL AND "
            " recommendation_algorithm_version IS NULL AND "
            " recommended_at IS NULL) OR "
            "(recommendation IS NOT NULL AND "
            " recommendation_algorithm_version IS NOT NULL AND "
            " recommended_at IS NOT NULL)",
            name=op.f("ck_lecturer_scopus_identities_recommendation_consistency"),
        ),
    )
    op.create_index(
        op.f("uq_identities_scopus_author_approved"),
        "lecturer_scopus_identities",
        ["scopus_author_id"],
        unique=True,
        postgresql_where=sa.text("status = 'APPROVED'"),
    )
    op.create_index(
        op.f("ix_identities_scopus_author_id"),
        "lecturer_scopus_identities",
        ["scopus_author_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_identities_status_updated"),
        "lecturer_scopus_identities",
        ["status", "updated_at"],
        unique=False,
    )

    # 12. identity_evidence -----------------------------------------------
    op.create_table(
        "identity_evidence",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=GEN_RANDOM_UUID,
        ),
        sa.Column("identity_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("evidence_type", sa.String(length=40), nullable=False),
        sa.Column("direction", sa.String(length=20), nullable=False),
        sa.Column("confidence_score", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("algorithm_version", sa.String(length=100), nullable=False),
        sa.Column("features", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source_refs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("evidence_fingerprint", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=NOW,
        ),
        sa.ForeignKeyConstraint(
            ["identity_id"],
            ["lecturer_scopus_identities.id"],
            name=op.f("fk_identity_evidence_identity_id_lecturer_scopus_identities"),
            ondelete="RESTRICT",
        ),
        sa.UniqueConstraint(
            "identity_id",
            "evidence_type",
            "algorithm_version",
            "evidence_fingerprint",
            name=op.f("uq_identity_evidence_dedup"),
        ),
        sa.CheckConstraint(
            "confidence_score >= 0.0 AND confidence_score <= 1.0",
            name=op.f("ck_identity_evidence_confidence_score"),
        ),
        sa.CheckConstraint(
            "direction IN ('SUPPORTS', 'CONTRADICTS')",
            name=op.f("ck_identity_evidence_direction"),
        ),
        sa.CheckConstraint(
            "evidence_type IN ("
            "'APPROVED_ID', 'ORCID_EXACT', 'DOI_EXACT', "
            "'PUBLICATION_OVERLAP', 'COAUTHOR_CONFIRMED', "
            "'NAME_SIMILARITY', 'AFFILIATION_MATCH')",
            name=op.f("ck_identity_evidence_evidence_type"),
        ),
        sa.CheckConstraint(
            "evidence_fingerprint ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_identity_evidence_fingerprint"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(features) = 'object'",
            name=op.f("ck_identity_evidence_features_object"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(source_refs) = 'array'",
            name=op.f("ck_identity_evidence_source_refs_array"),
        ),
    )
    op.create_index(
        op.f("ix_identity_evidence_created_at"),
        "identity_evidence",
        ["created_at"],
        unique=False,
    )

    # -------------------------------------------------------------------
    # CỤM 5: GOVERNANCE & AUDITING (users is a review prerequisite)
    # -------------------------------------------------------------------

    # 13. users -----------------------------------------------------------
    op.create_table(
        "users",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=GEN_RANDOM_UUID,
        ),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("lecturer_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("TRUE"),
        ),
        sa.Column(
            "version",
            sa.Integer(),
            nullable=False,
            server_default=sa.text("1"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=NOW,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=NOW,
        ),
        sa.ForeignKeyConstraint(
            ["lecturer_id"],
            ["lecturers.id"],
            name=op.f("fk_users_lecturer_id_lecturers"),
            ondelete="RESTRICT",
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_users_version")),
        sa.CheckConstraint("btrim(email) <> ''", name=op.f("ck_users_email_not_empty")),
        sa.CheckConstraint(
            "btrim(display_name) <> ''",
            name=op.f("ck_users_display_name_not_empty"),
        ),
        sa.CheckConstraint(
            "role IN ('ADMIN', 'REVIEWER', 'LECTURER')",
            name=op.f("ck_users_role"),
        ),
        sa.CheckConstraint(
            "role <> 'LECTURER' OR lecturer_id IS NOT NULL",
            name=op.f("ck_users_lecturer_account_required"),
        ),
    )
    op.create_index(
        op.f("uq_users_email_ci"),
        "users",
        [sa.text("lower(email)")],
        unique=True,
    )
    op.create_index(
        op.f("uq_users_lecturer"),
        "users",
        ["lecturer_id"],
        unique=True,
        postgresql_where=sa.text("lecturer_id IS NOT NULL"),
    )

    # CỤM 4 continued after its governance prerequisite.
    # 14. mapping_reviews -------------------------------------------------
    op.create_table(
        "mapping_reviews",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=GEN_RANDOM_UUID,
        ),
        sa.Column("identity_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("reviewer_user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("action", sa.String(length=20), nullable=False),
        sa.Column("from_status", sa.String(length=20), nullable=False),
        sa.Column("to_status", sa.String(length=20), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("evidence_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("compensates_review_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=NOW,
        ),
        sa.ForeignKeyConstraint(
            ["identity_id"],
            ["lecturer_scopus_identities.id"],
            name=op.f("fk_mapping_reviews_identity_id_lecturer_scopus_identities"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_user_id"],
            ["users.id"],
            name=op.f("fk_mapping_reviews_reviewer_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["compensates_review_id"],
            ["mapping_reviews.id"],
            name=op.f("fk_mapping_reviews_compensates_review_id_mapping_reviews"),
            ondelete="RESTRICT",
        ),
        sa.CheckConstraint(
            "action IN ('APPROVE', 'REJECT', 'REVOKE', 'REOPEN')",
            name=op.f("ck_mapping_reviews_action"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(evidence_snapshot) = 'object'",
            name=op.f("ck_mapping_reviews_evidence_snapshot_object"),
        ),
        sa.CheckConstraint(
            "(action = 'APPROVE' AND from_status = 'CANDIDATE' AND to_status = 'APPROVED') "
            "OR "
            "(action = 'REJECT'  AND from_status = 'CANDIDATE' AND to_status = 'REJECTED') "
            "OR "
            "(action = 'REVOKE'  AND from_status = 'APPROVED'  AND to_status = 'REVOKED') "
            "OR "
            "(action = 'REOPEN'  AND from_status IN ('REJECTED', 'REVOKED') "
            "                    AND to_status = 'CANDIDATE')",
            name=op.f("ck_mapping_reviews_transitions"),
        ),
        sa.CheckConstraint(
            "action = 'APPROVE' OR (reason IS NOT NULL AND btrim(reason) <> '')",
            name=op.f("ck_mapping_reviews_reason_required"),
        ),
        sa.CheckConstraint(
            "(action IN ('APPROVE', 'REJECT') AND compensates_review_id IS NULL) "
            "OR "
            "(action IN ('REVOKE', 'REOPEN') AND compensates_review_id IS NOT NULL)",
            name=op.f("ck_mapping_reviews_compensates"),
        ),
    )
    op.create_index(
        op.f("ix_mapping_reviews_identity_id"),
        "mapping_reviews",
        ["identity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_mapping_reviews_reviewer"),
        "mapping_reviews",
        ["reviewer_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_mapping_reviews_compensates"),
        "mapping_reviews",
        ["compensates_review_id"],
        unique=False,
        postgresql_where=sa.text("compensates_review_id IS NOT NULL"),
    )

    # 15. audit_events ----------------------------------------------------
    # Per §24: physical column is exactly `metadata`; the Python ORM
    # attribute is aliased to ``event_metadata`` in app.models.governance.
    op.create_table(
        "audit_events",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=GEN_RANDOM_UUID,
        ),
        sa.Column("entity_type", sa.String(length=100), nullable=False),
        sa.Column("entity_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("actor_type", sa.String(length=20), nullable=False),
        sa.Column("actor_user_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("actor_service", sa.String(length=100), nullable=True),
        sa.Column("before_state", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("after_state", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("request_id", sa.String(length=128), nullable=True),
        sa.Column("correlation_id", sa.String(length=128), nullable=True),
        sa.Column("ip_address", postgresql.INET(), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        # Physical DB column is `metadata`; NEVER `event_metadata`.
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=NOW,
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_audit_events_actor_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.CheckConstraint(
            "actor_type IN ('USER', 'SYSTEM')",
            name=op.f("ck_audit_events_actor_type"),
        ),
        sa.CheckConstraint(
            "entity_type ~ '^[a-z][a-z0-9_]*$'",
            name=op.f("ck_audit_events_entity_type_format"),
        ),
        sa.CheckConstraint(
            "action ~ '^[A-Z][A-Z0-9_]*$'",
            name=op.f("ck_audit_events_action_format"),
        ),
        sa.CheckConstraint(
            "(actor_type = 'USER' AND actor_user_id IS NOT NULL "
            "                       AND actor_service IS NULL) "
            "OR "
            "(actor_type = 'SYSTEM' AND actor_user_id IS NULL "
            "                         AND actor_service IS NOT NULL "
            "                         AND btrim(actor_service) <> '')",
            name=op.f("ck_audit_events_actor_invariant"),
        ),
        sa.CheckConstraint(
            "before_state IS NULL OR jsonb_typeof(before_state) = 'object'",
            name=op.f("ck_audit_events_before_state_object"),
        ),
        sa.CheckConstraint(
            "after_state IS NULL OR jsonb_typeof(after_state) = 'object'",
            name=op.f("ck_audit_events_after_state_object"),
        ),
        sa.CheckConstraint(
            "metadata IS NULL OR jsonb_typeof(metadata) = 'object'",
            name=op.f("ck_audit_events_metadata_object"),
        ),
    )
    op.create_index(
        op.f("ix_audit_events_entity"),
        "audit_events",
        ["entity_type", "entity_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_events_actor"),
        "audit_events",
        ["actor_user_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_events_created"),
        "audit_events",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_events_correlation"),
        "audit_events",
        ["correlation_id"],
        unique=False,
        postgresql_where=sa.text("correlation_id IS NOT NULL"),
    )


def downgrade() -> None:
    """Drop the 15 application tables in dependency-safe reverse order.

    Per §26, no shortcut CASCADE is used; the explicit order resolves
    the FK dependency graph deterministically.
    """
    # CỤM 5 / CỤM 4
    op.drop_table("audit_events")
    op.drop_table("mapping_reviews")
    op.drop_table("users")
    op.drop_table("identity_evidence")
    op.drop_table("lecturer_scopus_identities")

    # CỤM 3
    op.drop_table("publication_authors")
    op.drop_table("scopus_author_name_variants")
    op.drop_table("scopus_authors")
    op.drop_table("publication_raw_sources")
    op.drop_table("publications")

    # CỤM 2
    op.drop_table("raw_scopus_records")
    op.drop_table("scopus_imports")

    # CỤM 1
    op.drop_table("lecturer_known_publications")
    op.drop_table("lecturer_source_snapshots")
    op.drop_table("lecturers")
